### ISSUE TITLE
Cannot find module 'art/core/path.js'.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [Root-App/react-native-mock-render#47]
Following a basic setup, I get the following error running on Jest 22:

```
 FAIL  frontend/native/screens/__tests__/concentration_screen_spec.js
  ● Test suite failed to run

    Cannot find module 'art/core/class.js' from 'Path.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-native-mock-render/build/components/ART/Path.js:1:104)
```

Searching around in the codebase, I don't see any files that match `art/core/class.js`. I've had to comment out the `ART` component in `react-native.js` on line 13.

Anyone know what's going on there?

**Comment by chinenyem** [comment]
I am having the same issue, has anyone come up with an answer for this yet?

**Comment by DracotMolver** [comment]
This is because the ART dependency was removed from the react-native core. This project seems not to be maintain. If you look the code the mock is pointed to an non-existent class. It should be updated. A quick/awful part is just comment the line that calls the ART dependency or make a fork of this project and fix it by your own

**Comment by GhayoorUlHaq** [comment]
Is there any solution for this?

**Comment by sonicdoe** [comment]
@russellwpatterson Why did you close this issue?

**Comment by russellwpatterson** [comment]
Accidentally. I can reopen.

**Comment by sonicdoe** [comment]
Thank you! By the way, this issue should be fixed by https://github.com/Root-App/react-native-mock-render/pull/89.
